version: '3.7'

services:
  wp-db:
    image: mariadb
    container_name: wp-db
    ports:
      - '8086:3306'
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  wp-webserver:
    image: nginx:latest
    container_name: wp-webserver
    depends_on:
      - wp-files
    ports:
      - '8084:80'
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/conf.d/ssl
    volumes_from:
      - wp-files
  wp-files:
    image: wordpress:5.7.2-php7.4-fpm-alpine
    container_name: wp-files
    depends_on:
      - wp-db
    volumes:
      - ./wp-files:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
      - wp-db:mysql
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
  wp-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp-phpmyadmin
    depends_on:
      - wp-db
    ports:
      - '8085:80'
    links:
      - wp-db:db
